# Generated by Django 5.2 on 2025-05-06 05:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='cld-sample-4', max_length=255, verbose_name='image'),
        ),
    ]
