# Generated by Django 5.2 on 2025-05-06 05:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_item', '0002_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1746180583/cld-sample-4.jpg', max_length=255, verbose_name='image'),
        ),
    ]
