# Generated by Django 5.2 on 2025-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='didar'),
            preserve_default=False,
        ),
    ]
